# Generated by Django 4.0.5 on 2022-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
    ]
