# Generated by Django 4.0.5 on 2022-06-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0003_remove_news_image_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
