# Generated by Django 4.0.5 on 2022-06-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0004_alter_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999999999999999999999)),
                ('describtion', models.CharField(max_length=999999999999999999999)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
