# Generated by Django 4.0.5 on 2022-06-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.CharField(blank=True, max_length=99999999999),
        ),
    ]
