# Generated by Django 4.0.5 on 2022-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0007_news_imgpath_alter_news_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='imgpath',
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='img/'),
        ),
    ]
