# Generated by Django 4.0.5 on 2022-06-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0015_alter_news_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
    ]
