# Generated by Django 4.0.5 on 2022-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0016_remove_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=999999999999999999999, unique=True),
        ),
    ]
