# Generated by Django 4.0.5 on 2022-06-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verein', '0017_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=999999999999999999999, unique=True),
        ),
    ]
